[package]
name = "critical-section"
version = "0.2.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"
description = "Critical section abstraction"
repository = "https://github.com/embassy-rs/critical-section"
readme = "README.md"
license = "MIT OR Apache-2.0"
categories = [
    "embedded",
    "no-std",
    "concurrency",
]

[features]
custom-impl = []

[dependencies]
bare-metal = "1.0.0"
cfg-if = "1.0.0"

[target.thumbv6m-none-eabi.dependencies]
cortex-m = "0.7.2"
[target.thumbv7em-none-eabi.dependencies]
cortex-m = "0.7.2"
[target.thumbv7em-none-eabihf.dependencies]
cortex-m = "0.7.2"
[target.thumbv7m-none-eabi.dependencies]
cortex-m = "0.7.2"
[target."thumbv8m.base-none-eabi".dependencies]
cortex-m = "0.7.2"
[target."thumbv8m.main-none-eabi".dependencies]
cortex-m = "0.7.2"
[target."thumbv8m.main-none-eabihf".dependencies]
cortex-m = "0.7.2"
